#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# close tray if reloading
killall stalonetray


# lock screen
#hc keybind $Mod-x	spawn bash /home/ns/.local/bin/lock

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
Mod=Mod1    # Use alt as the main modifier
#Mod=Mod4   # Use the super key as the main modifier

# scrot
#hc keybind $Mod-F12 spawn scrot -e 'mv $f ~trove/images/misc/scrots/ns/'

# dynamic window gap
hc keybind $Mod-9	spawn zsh /home/ns/.local/bin/herbstluftwm-remove-gap
hc keybind $Mod-0	spawn zsh /home/ns/.local/bin/herbstluftwm-add-gap
hc keybind $Mod-b spawn zsh /home/ns/.local/bin/s-bat -c
hc keybind $Mod-t spawn zsh /home/ns/.local/bin/s-date
#hc keybind $Mod-v spawn zsh /home/ns/.local/bin/s-weather #
#
# Navigering i Firefox med Alt+a och Alt+d


hc keybind $Mod-Control-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Control-x spawn /usr/bin/zsh -c 'shutdown now'
hc keybind $Mod-q close
hc keybind $Mod-Return spawn urxvtc
hc keybind $Mod-d spawn /usr/bin/zsh -c 'dmenu_run'
hc keybind $Mod-w spawn firefox

# basic movement in tiling and floating mode
# focusing clients
#hc keybind $Mod-Left  focus left
#hc keybind $Mod-Down  focus down
#hc keybind $Mod-Up    focus up
#hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       chain , split   bottom  0.5  , focus down #row
hc keybind $Mod-o       chain , split   right   0.5  , focus right #column
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode


# resizing frames and floating clients
resizestep=0.01
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {0..4} )
tag_keys=( {1..5} 0 )

# set up normal tags
hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
	key="${tag_keys[$i]}"
	layoutfile=/home/ns/dot/herbstluftwm/layout-${key}
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" \
			chain , silent substitute M tags."$i".my_monitor \
					focus_monitor M \
				, use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
		if [ -f ${layoutfile} ] ; then
			hc load ${i} "$(cat ${layoutfile})"
		fi
    fi
done

hc keybind $Mod-y chain \
	, new_attr string tags.focus.my_monitor \
	, substitute M monitors.focus.index set_attr tags.focus.my_monitor M \
	, try and \
		. compare monitors.focus.name != "" \
		. substitute M monitors.focus.name \
			set_attr tags.focus.my_monitor M

hc keybind $Mod-Shift-t \
	remove_attr tags.focus.my_monitor

lock_tag_to_monitor() {
	hc chain \
		, new_attr string tags.by-name."$1".my_monitor \
		, set_attr tags.by-name."$1".my_monitor "$2"
}

lock_tag_to_monitor 0 0
lock_tag_to_monitor 1 1
lock_tag_to_monitor 2 0
lock_tag_to_monitor 3 1
lock_tag_to_monitor 4 0

# cycle through tags


# layouting
hc keybind $Mod-x remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-Shift-space cycle_layout -1
hc keybind $Mod-s set_attr clients.focus.floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent
hc set focus_follows_mouse 1

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#262626'
hc set frame_border_normal_color '#191919'
hc set frame_bg_normal_color '#262626'
hc set frame_bg_active_color '#191919'
hc set frame_border_width 0
hc set always_show_frame on
hc set frame_bg_transparent on
hc set frame_transparent_width 0
hc set frame_gap 20

hc attr theme.title_height 0
hc attr theme.padding_top 0
hc attr theme.active.color '#262626'
hc attr theme.normal.color '#262626'
# hc attr theme.floating.active.color '#262626'
# hc attr theme.floating.normal.color '#262626'
hc attr theme.urgent.color '#ac8a8c'
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 0
hc attr theme.floating.border_width 0
hc attr theme.floating.padding_top 0
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color "#262626"
hc attr theme.active.inner_color '#262626'
hc attr theme.active.outer_color '#262626'
hc attr theme.background_color '#262626'


hc set window_gap 10
hc set frame_padding -5
hc set smart_window_surroundings off
hc set smart_frame_surroundings off
hc set mouse_recenter_gap 0

hc set snap_distance 14
hc set snap_gap 9
hc set snap_to_edge 1

# Set default frame layout to grid (3)
hc set default_frame_layout 3

# Apply the default frame layout to existing tags
hc substitute 3 settings.default_frame_layout \
    foreach T tags.by-name. \
    sprintf ATTR '%c.tiling.root.algorithm' T \
    set_attr ATTR 3

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=on

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

hc rule class=firefox tag=1
hc rule title=dmenu floating=true

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors
